#!/bin/bash

echo ""
echo "                                      Command List                                   "
echo "-------------------------------------------------------------------------------------"
echo ""
echo "./run.sh - Loads the entire Project Packrat interface"
echo ""
echo "./run.sh <command> - where command is: "
echo ""
echo "         -add:     runs the Add Device module"
echo "         -search:  runs the Lookup Device module"
echo "         -archive: runs the Archive Config module"
echo "         -apply:   runs the Apply Template module"
echo "         -new:     runs the Create New Template module"
echo "         -view:    runs the View or Edit Templates module"
echo "         -ssh:     runs the SSH module (NOT IMPLEMENTED YET)"
echo ""
echo "./run.sh <command> <argument1> <argument2> <argument3> <argument4>":
echo ""
echo "         -add <hostname> <ip>: adds a device with the specified characteristics"
echo "         -add <hostname>:      prompts for an IP and then adds the device"
echo ""
echo "         -search <hostnameOrIP>: looks for device matching hostname or IP"
echo ""
echo "         -archive <hostnameOrIP>: archives configs for device matching hostname or IP"
echo ""
echo "         -new <model> <templateName> <txtEditor>: creates <templateName>.template for"
echo "					          <model> and opens the file in the"
echo " 						  <txtEditor>"
echo "                                     <txtEditor>: vim or nano"
echo ""
echo "         -new <model> <templateName>: creates a file but prompts for a text editor"
echo "         -new <model>:                prompts for templateName and text editor"
echo ""
echo "  clear  - Clears the screen"
echo ""
